### ISSUE TITLE
auth

### ISSUE THREAD

**Issue by fernandex00** [custom-components/sensor.trakt#18]
hi i get this error getting the auth for trakt
![2d9750a9-fe59-4273-8143-ff66f6ef0b18 png](https://user-images.githubusercontent.com/34770145/52181300-bf6b5100-27c6-11e9-9396-cfde0795fec8.jpg)

**Comment by MatteGary** [comment]
me too, any news?

**Comment by iantrich** [comment]
I haven't had a chance to look at this yet

**Comment by MatteGary** [comment]
I think it is a misconfiguration problem between trakt and HA. What URI should I put in the Trakt API page in the Redirect URI field?

**Comment by iantrich** [comment]
`urn:ietf:wg:oauth:2.0:oob`

**Comment by MatteGary** [comment]
great it works.
there should be a step somewhere in the doc of this component

**Comment by iantrich** [comment]
It is mentioned when you create a new app in Trakt, so didn't think it was necessary.
![image](https://user-images.githubusercontent.com/1287159/52484094-1c765680-2b7b-11e9-801e-0226af56c41c.png)
Feel free to add it to the Readme

**Comment by iantrich** [comment]
@fernandex00 please let me know if this resolves your issues as well

**Comment by fernandex00** [comment]
It's working now sorry for the delay
