### ISSUE TITLE
Changes in Hassio 0.88

### ISSUE THREAD

**Issue by r3m0dul8** [custom-components/sensor.trakt#19]
Hey buddy, something you may want to work into your wiki as changes to 0.88 have constants moved so therefore locations are broken.

Fix for this in config/custom_components make a new dir called "trakt" and move the file "trakt.py" from config/custom_components/sensor/ to newly created folder config/custom_components/trakt/ then rename file from "trakt.py" to "sensor.py"

Done, not an issue but I believe efficiency is key

Dave.

**Comment by iantrich** [comment]
You mean like this https://github.com/custom-components/sensor.trakt/issues/15

;)
