### ISSUE TITLE
Got sensor and state (number of shows) but no shows

### ISSUE THREAD

**Issue by onkelfarmor** [custom-components/sensor.trakt#21]
I get my sensor but it’s quite empty - only the number of shows (state) is correct.

> data: [{“title_default”: “$title”, “line1_default”: “$episode”, “line2_default”: “$release”, “line3_default”: “$rating - $runtime”, “line4_default”: “$number - $studio”, “icon”: “mdi:arrow-down-bold”}]
> unit_of_measurement: shows
> friendly_name: Trakt Upcoming Calendar
> icon: mdi:calendar

**Comment by iantrich** [comment]
No errors in the log?

**Comment by onkelfarmor** [comment]
Nothing at all :-(

**Comment by iantrich** [comment]
@maykar mentioned that you had a show that didn't have seasons, some news program?

**Comment by onkelfarmor** [comment]
I only had one show in my calendar:
https://trakt.tv/shows/grey-s-anatomy

I tried adding another active show, and now my sensor shows 6 in state (was 3 before) and the next 3 episodes from the new show is shown in the component. 

So it must have something to do with Grey’s Anatomy.

**Comment by laz3rpenguin** [comment]
I have the same response. I only have A.P Bio in my trakt. Looking in the log:
`2019-06-03 11:49:22 DEBUG (SyncWorker_0) [trakt.core] RESPONSE [get] (https://api-v2launch.trakt.tv/search?query=a-p-bio&type=show): <Response [200]>`
Looks like it is querying trakt. Amount of upcoming shows is correct, but none of the other data is there. Just like OP.

**Comment by iantrich** [comment]
Very strange. I'll see about creating a test trakt account with just those shows and see what I can find.

**Comment by marrobHD** [comment]
In my log are no errors, but sensor.trakt_upcoming_calendar stays as unknown

**Comment by iantrich** [comment]
@marrobHD do you have a similar setup where you only have a single show? I've been lazy this summer and not doing much coding so haven't gotten around to looking at this.

**Comment by marrobHD** [comment]
Yes ists similar

**Comment by iantrich** [comment]
Which show?

**Comment by marrobHD** [comment]
What do you mean?

**Comment by iantrich** [comment]
I'm trying to narrow down if there is some commonality between shows. What show are you tracking?

**Comment by marrobHD** [comment]
Ooopps i never selected something. How can I select a show to track. Ouuf

**Comment by iantrich** [comment]
You do that on trakt.tv

**Comment by marrobHD** [comment]
https://n8970q34vnvidunh897qfc5wenh87v.tk/s/eYjPqb54QRryaZT/preview
Which button?

**Comment by iantrich** [comment]
Just go here: https://trakt.tv/
Sign in and start managing your shows

**Comment by marrobHD** [comment]
Ive made it already but nothing

**Comment by laz3rpenguin** [comment]
I think it must have something to do with the shows. Some will display and
others won't... I couldn't get AP Bio to display (while it was an active
series), but Billions would. Might be worth waiting until returning series
start up again later in the year to analyze them a bit better.

**Comment by iantrich** [comment]
I'm wondering if it was the punctuation in those shows that was tripping things up when doing the additional queries against tvdb for artwork and additional series data.

**Comment by mbrihed** [comment]
Hi!
I have a similar problem. This was working great for a few weeks. Now I only get Billions to show. In trakt.tv I see there are more (at least 3 shows today) in my dashboard (Upcoming Schedule).
I have removed the integration. cleaned up the manual entries I had from before. I have re-auth the app again. It all connects fine and re-auth. I have the sensor and the card in lovelace.ui. However only Billions shows up.

**Comment by mbrihed** [comment]
Hi!
Mine started working again, no idea what caused the issue. I now get shows and everything seems to be fine.
