### ISSUE TITLE
Cannot change integration options on the Trakt.tv integration page

### ISSUE THREAD

**Issue by jayscovill** [custom-components/sensor.trakt#36]
## Version of Home Assistant
.108.6

## Version of the custom_component
1.1.0

## Describe the bug
When trying to change the "Update frequency" or "Days to look forward" options for the integration it returns "User input malformed".

**Comment by engrbm87** [comment]
It turns out that the `list of excluded shows` field can't be left blank. A workaround is just to enter a whitespace in the excluded field.
