### ISSUE TITLE
The trakt platform for the sensor integration does not support platform setup. Please remove it from your config.

### ISSUE THREAD

**Issue by ikrowni** [custom-components/sensor.trakt#37]
## Version of Home Assistant

0.108.9

## Version of the custom_component

1.1.0

## Configuration

  - platform: trakt
    id: 'REDACTED'
    secret: 'REDACTED'
    username: REDACTED
    days: 10
    name: Trakt James Calendar

and

  - platform: trakt
    id: 'REDACTED'
    secret: 'REDACTED'
    username: REDACTED
    days: 10
    name: Trakt Kathys Calendar

Add your logs here.

The trakt platform for the sensor integration does not support platform setup. Please remove it from your config.

## Describe the bug

It seems like the trakt configuration now goes directly into configuration.yaml instead of belonging in sensors. I had 2 seperate calendars i was feeding into home assistant does this mean i can only have 1 now?

**Comment by iantrich** [comment]
1.1.0 introduced a breaking change. Use this
```yaml
trakt:
  client_id: <client_id>
  client_secret: <client_secret>
```
And then you should be able to add the integration twice from the UI for the different calendars.

**Comment by ikrowni** [comment]
Now im getting this error when i try to sign into trakt

```
OAUTH ERROR
The requested redirect uri is malformed or doesn't match client redirect URI.
```

**Comment by iantrich** [comment]
check the readme

**Comment by ikrowni** [comment]
![Screenshot_20200425-144804](https://user-images.githubusercontent.com/4442098/80288144-f26b6e80-8703-11ea-836e-98367a47c138.png)


I've made sure to add the uri callbacks as stated in the readme. I use home assistant cloud so I chose the first option then in the second line I added the other uri you specified. I'm still getting the error though.

**Comment by honkerst** [comment]
Just adding that I'm having the same issue.  I had configured Trakt and set it up about a month ago. It was working and displaying my watched shows in my lovelace UI until about a week ago. 

Now I've read this and moved my config to configuration.yaml, but when I add the integration I get the same OAuth error as @ikrowni.

**Comment by ikrowni** [comment]
> Now I've read this and moved my config to configuration.yaml, but when I add the integration I get the same OAuth error as @ikrowni

Someone else just helped me fix mine. I stead of using the nabucasa address you pretty much have to use your internal up address instead. So put it like this

`http://<local-ip>:<port>/auth/external/callback` and it should work

**Comment by ikrowni** [comment]
Okay I got the trakt integration working but like I previously asked. How do I get more than 1 trakt account working with this method? I'm not seeing the option to add anything like my wife's client id and secret to add her account as a secondary.

**Comment by ninjax95** [comment]
> check the readme

Thanks, but do you know how to exclude some tvshow ?

**Comment by iantrich** [comment]
I don't have answers for you guys, @engrbm87 introduced the config flow and I'm not 100% up to speed on the limitations of that method and don't really have the time right now to dig into it. I'd recommend just using the previous version for now as there was really no functional change with the 1.1.0 release, just the config flow.

**Comment by ikrowni** [comment]
Yea that's pretty much what I decided to do yesterday. I can't see how there would be much difference and the plugin was working great before. Thanks for the great addon hopefully you can fix up the newer version sometime but I'm not in a big hurry for it. Take your time.

**Comment by engrbm87** [comment]
The new version uses the built-in OAuth2Session in home assistant. I am trying to see if there is a way to support multiple instances but until now I can't find it.
