### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by cgorms** [custom-components/sensor.trakt#39]
Home Assistant Version 0.109.2

trakt - Installed: 1.1.0
Upcoming Media Card - Installed: 0.4.0

## Configuration

trakt:
    client_id: '<client_id>'
    client_secret: '<client_secret>'

Lovelace UI
type: 'custom:upcoming-media-card'
entity: sensor.trakt_upcoming_calendar
title: Upcoming Movies/Shows
clock: 24

## Describe the bug
Upcoming Media Card is not working - it's blank with only the tilt showing though there is the debug log below assume this is related to why it may not be working.

## Debug log

Logger: homeassistant.helpers.translation
Source: helpers/translation.py:206 
First occurred: 1:26:29 AM (2 occurrences) 
Last logged: 1:26:30 AM

trakt: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this

**Comment by iantrich** [comment]
That is not likely related, that's about an upcoming change. First verify the sensor exists and has data. The Lovelace card being populated is a secondary thing and could be totally unrelated

**Comment by engrbm87** [comment]
Hello @cgorms , Have you tried updating to the latest version. If this issue is still present let us know.

**Comment by engrbm87** [comment]
Closing this issue as this should be resolved in the latest release.
