### ISSUE TITLE
OAUTH error about malformed redirect URL on registration

### ISSUE THREAD

**Issue by groenmarsmannetje** [custom-components/sensor.trakt#42]
## Version of Home Assistant

0.109.3

## Version of the custom_component

2.0.0

## Configuration

N.a.

## Describe the bug

When I try to register this integration with the new UI integration then I get the following OAUTH error on the Trakt website “The requested redirect uri is malformed or doesn't match client redirect URI.”

## Debug log

N.a.

**Comment by engrbm87** [comment]
Make sure the `redirect_url` showing in the address bar of the opened page is configured in your application settings on Trakt website.
