### ISSUE TITLE
Oauth error (searched closed issues but can't get it working)

### ISSUE THREAD

**Issue by eoren1** [custom-components/sensor.trakt#44]
Home Assistant 0.110.1
Trakt Installed: 2.0.0

I've looked at closed issued but have tried every solution presented but continue to get Oauth/malformed url errors.

In Trakt application, I have tried individually:
https://XXXXXX.ui.nabu.casa/auth/external/callback
OR
http://192.168.1.40:/auth/external/callback
OR
urn:ietf:wg:oauth:2.0:oob

If I click the Authorize button in the Trakt application for each of those, only the urn 'works' and gives me a pin - but then I never get to the point of being able to add a pin within the HA - Configuration - Integration - Add part after putting in the Client ID and secret

I have also tried a combo of inputting both 
urn:ietf:wg:oauth:2.0:oob
https://XXXXXX.ui.nabu.casa/auth/external/callback

But again got the Oauth error page on Trakt

I do not see anything in Developer  Tools - Logs to guide me

Thanks and sorry if I'm missing something obvious

**Comment by engrbm87** [comment]
The pin code is no longer used. You need to follow the steps mentioned in the [READEME ](https://github.com/custom-components/sensor.trakt/blob/master/README.md)file and configure the integration using HA UI.

**Comment by eoren1** [comment]
Thank you. I only tried the pin code when the first two did not work.

I have tried doing exactly what the Readme states step by step but still get Oath Error - the requested redirect url is malformed or doesn't match client redirect url.

Here is what I did now:
Made two new apps in https://trakt.tv/oauth/applications
One used the HA cloud redirect - https://XXXXXXX.ui.nabu.casa/auth/external/callback
Other used the local redirect - http://192.168.1.40:/auth/external/callback 
Saved both

I had installed Trakt via HACS. Restarted. Went to Configuration - Integrations - PLUS sign - Trakt

I put in the ID and secret each time and both gave Oauth errors

On the Trakt app page, I clicked the Authorize button next to the redirect URL for each app I made as above.  Both sent me to a page asking me to 'Allow the app to use your account' but when I said yes, the one for the cloud gave this warning:
Missing code or state parameter in https://XXXXX.ui.nabu.casa/auth/external/callback?code=4b0b7bbf2997298eca61cbe57391f32a0XXXXXXXXXX
The local one just opened up my Synology NAS url

**Comment by eoren1** [comment]
I'm an idiot.

In case anyone searches in the future - I forgot the local port...

What might be helpful if this occurs in the future is to point newbies to the HA - Configuration - General where both External (mine is blank) and Internal (where I discovered the port was missing) are listed.
