### ISSUE TITLE
Option to add Anticipated Trakt feeds

### ISSUE THREAD

**Issue by eoren1** [custom-components/sensor.trakt#45]
Now that I have the Trakt integration running, I find that it is only able to mirror my Sonarr Upcoming TV list.  I do not have Trakt VIP and thus do not have custom calendar/subscribing options.

Would it be possible to add some of the Official Trakt Lists (especially Anticipated Movies and Anticipated TV) to the media card? 

Thanks

**Comment by engrbm87** [comment]
This is not currently available in the [PyTrakt](https://github.com/moogar0880/PyTrakt) which is the library used by this component. Once it becomes available we can try to add it.
