### ISSUE TITLE
OAUTH ERROR - The requested redirect uri is malformed or doesn't match client redirect URI.

### ISSUE THREAD

**Issue by CM000n** [custom-components/sensor.trakt#46]
## Version of Home Assistant
0.111.2

## Version of the custom_component
2.0.0

## Describe the bug
I installed the plugin via HACS. Every time I try to add it as an integration via the GUI, it wants to redirect me to Trakt Oauth authentication. 
Trakt will always call http://172.20.0.9:8123/auth/external/callback as redirect_uri, no matter what I have specified as redirect_uri within Trakt for my app.
Since the 172.20.0.9 does not exist within my network, this of course leads to an error message and I cannot authenticate myself.
I don't know if this is a problem of the tract HA integration or tract itself.

## Debug log
![3456435345](https://user-images.githubusercontent.com/7945681/84593791-554ccc80-ae4e-11ea-9920-eb8a491820b6.JPG)
![65767657nt](https://user-images.githubusercontent.com/7945681/84593810-70b7d780-ae4e-11ea-9168-adc316f0f390.JPG)

**Comment by engrbm87** [comment]
The latest version of HA introduced a new config option called 'Internal URL' under General. Make sure to enter your local HA address there.

**Comment by CM000n** [comment]
Hello @engrbm87 , thank you very much for this hint!
In fact, authentication now works for me after adding an 'Internal URL' to my HA config.

Now I am merely struggling with this problem: https://github.com/custom-components/sensor.trakt/issues/40
But therefore this ticket can be closed.
