### ISSUE TITLE
[Enhancement] Implement Event creation whenever a show is starting

### ISSUE THREAD

**Issue by caffeinatedMike** [custom-components/sensor.trakt#5]
Add event functionality, creating/firing an event whenever a show is starting. This will allow users to create automations, such as blink the lights to remind everyone the show's about to start.

**Comment by iantrich** [comment]
Great ideas. Thanks. This component was primarily focused on Lovelace consumption, that’s for sure. Primarily the list_card I made. Hopefully I can find sometime to look into some of these soon. 

Would you mind breaking these up into individual ones?

**Comment by iantrich** [comment]
@caffeinatedMike 
If I followed what you said about the upcoming media card is that you want something similar in a more-info modal. That's seems like a lot of work for something that is close to being obsolete is my thought. I haven't tried, but you might be able to define the list-card for your trakt feed in a single view and throw it into an iframe on the old front-end?

**Comment by caffeinatedMike** [comment]
@iantrich I just got done breaking out the feature requests into separate issues for better organization. I guess you're right, I've just been avoiding trying Lovelace because I barely just got up to speed with the current evironment, being so new to the scene.

**Comment by iantrich** [comment]
Cleaned up comments
