### ISSUE TITLE
OAuth2 URI not working

### ISSUE THREAD

**Issue by remyderuysscher** [custom-components/sensor.trakt#50]
Created an app, used the correct redirect URI, callback fails seems HA issue?

URI: http://10.50.2.177:8123/auth/external/callback

After clicking Authorize I get this HA error message:

Missing code or state parameter in http://10.50.2.177:8123/auth/external/callback?code=XXXXXXXXXXX (removed code)

**Comment by gdreelin** [comment]
I noticed mine stopped working so I checked it and the OAuth2 was missing. I put it there awhile back but it was gone. I did the url for the cloud link but getting the same response of missing code.

**Comment by gdreelin** [comment]
It stated in issue #18 (https://github.com/custom-components/sensor.trakt/issues/18) to add "urn:ietf:wg:oauth:2.0:oob" to the Redirect URI but I am not following how to add it. Do we still need the original "https://<cloud-remote-url>/auth/external/callback" part? I tried it with and without but no joy either way. This was working great then all of a sudden just stopped working.

**Comment by iantrich** [comment]
https://github.com/custom-components/sensor.trakt/issues/46#issuecomment-644044024
