### ISSUE TITLE
Poster / Fanart Issues.

### ISSUE THREAD

**Issue by gdreelin** [custom-components/sensor.trakt#53]
How can you make is it does not pull posters of shows that were back many years ago (example: Magnum PI (1980) and now Magnum PI (2019)) It keeps pulling the old show poster from TVDB. Can this be fixed or is this an issue with Trakt?

**Comment by iantrich** [comment]
Trakt gives the TMDB id which we use to look up against the TMDB api. So either Trakt has the wrong TMDB id or TMDB has the wrong poster art for that show.
