### ISSUE TITLE
[Enhancement] Format data to be ingested by Upcoming Media card

### ISSUE THREAD

**Issue by caffeinatedMike** [custom-components/sensor.trakt#6]
- [ ] Implementing something like the [Upcoming Media Card](https://github.com/custom-cards/upcoming-media-card). This way we can see which shows are upcoming. Currently all we see is the number and, when clicked, a jumbo json object.
   **Example views taken from their README.md**
   ![Poster View](https://i.imgur.com/TALfNSy.jpg) ![Fan Art View](https://i.imgur.com/Xa6ksSz.jpg)
- [ ] In order for the above feature to obtain details (mainly images) from tmdb & tvdb I propose we add the following config values
      - tmdb_key ([TMDB Api Documentation](https://developers.themoviedb.org/3/getting-started))
      - tvdb_key ([TVDB Api Documentation](https://api.thetvdb.com/swagger))

**Comment by iantrich** [comment]
UI work is outside the scope of the project. Formatting the data so that it could be ingested by the Upcoming Media card is doable, however.

**Comment by iantrich** [comment]
https://github.com/custom-cards/upcoming-media-card

**Comment by maykar** [comment]
Recently updated upcoming-media-card to make this easier. Check out the bottom of the [readme](https://github.com/custom-cards/upcoming-media-card) for instructions. Takes JSON from sensor now.

Also, check out my [Radarr component](https://github.com/custom-components/sensor.radarr_upcoming_media). I use tmdb in it to grab additional info and images for movies, but they have TV shows as well. You can get a dev API key from them easily so you don't need the user to add their own to config.  Dev keys limit is 40 calls every 10 seconds, but more importantly the limit is per IP address not API key. They do have attribution requirements though. You can see it in Radarrs readme.

**Comment by quthla** [comment]
Is there any news on this? I use trakt to too so this would be great.

**Comment by iantrich** [comment]
No. I've been pretty busy contributing to the main HA repo for Lovelace stuff

**Comment by iantrich** [comment]
Done in latest release
