### ISSUE TITLE
[Enhancement] Allow creation of multiple sensors for grouping shows (ie by genre)

### ISSUE THREAD

**Issue by caffeinatedMike** [custom-components/sensor.trakt#7]
Allow the user to create multiple sensors & group shows under a single sensor, for example by genre. This would allow them to potentially group all anime shows into one sensor & all drama shows into another sensor and fire events separately. 

**Bonus:** Possibly allow a single sensor to list all show names under that group/genre and the air dates of their next episodes (only if they fall within the configured `day` setting in `configuration.yaml`)

# **Example:** 
**Configuration:**
Under the Upcoming Drama sensor, user configures `days` to 1 & adds three shows:
1. "How to Get Away with Murder" (Airs Thursdays)
2. "Scandel" (Airs Thursdays)
3. "The Good Doctor" (Airs Mondays)

**Scenario:**
If it's wednesday night, then the Drama sensor would list "How to Get Away with Murder" & "Scandel" & the date/time of the next episode. Since "The Good Doctor" isn't airing in the next 24 hours it would not be shown on the Upcoming Drama Sensor at that time.

**Comment by iantrich** [comment]
Genre is not available via PyTrakt: https://pytrakt.readthedocs.io/en/latest/tv.html#trakt.tv.TVShow

**Comment by caffeinatedMike** [comment]
Oh, my bad! But, maybe this could be generalized to "Allow a sensor per show"?

**Comment by iantrich** [comment]
Beyond the old/current UI, is there really a use case for that assuming we fire events on new shows?

**Comment by caffeinatedMike** [comment]
After fiddling a bit, I think no. In that case, we can consider this issue closed.
