### ISSUE TITLE
Missing State Parameter

### ISSUE THREAD

**Issue by aliekiddo** [custom-components/sensor.trakt#71]
I've setup the app with Redirect URL as http://192.168.1.2:8123/auth/external/callback

I've restarted HA but all I'm getting when I authorise the app is a page that says 'Missing state parameter'

When I add the integration, add in the client ID and client secret I get a page that says:

OAUTH ERROR
The requested redirect uri is malformed or doesn't match client redirect URI.

**Comment by LEdiodes** [comment]
Try setting the redirect URL to;

https://my.home-assistant.io/redirect/oauth

That should work for you

**Comment by skank01** [comment]
> Try setting the redirect URL to;
> 
> https://my.home-assistant.io/redirect/oauth
> 
> That should work for you

i have the same issue as topic starter.
Adding redirect/oauth didnt fix it

**Comment by poudenes** [comment]
Have same issue:

Core: 2024.1.2
Supervisor: 2023.12.0
Operating System: 11.4
Frontend: 20240104.0

Followed the rules and after reading this issue I used : https://my.home-assistant.io/redirect/oauth
and worked. 

Maybe you gave to update the information?
